# Generated by Django 5.2.1 on 2026-06-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='car',
            new_name='core_car_status_f133b0_idx',
            old_name='core_car_status_554294_idx',
        ),
        migrations.RenameIndex(
            model_name='car',
            new_name='core_car_vin_60390e_idx',
            old_name='core_car_vin_bf8a75_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='core_expens_car_id_ed82a9_idx',
            old_name='core_expens_car_id_6076ef_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='core_expens_categor_974cef_idx',
            old_name='core_expens_categor_2ec09b_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='core_expens_employe_85342e_idx',
            old_name='core_expens_employe_70da07_idx',
        ),
        migrations.AddField(
            model_name='car',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='repair_stage',
            field=models.CharField(choices=[('accepted', 'Принят в работу'), ('defect', 'Дефектовка'), ('waiting_parts', 'Ожидание деталей'), ('body_work', 'Кузовные работы'), ('preparation', 'Подготовка'), ('painting', 'Покраска'), ('assembly', 'Сборка'), ('polishing', 'Полировка'), ('ready', 'Готов к выдаче'), ('done', 'Завершен')], default='accepted', max_length=32, verbose_name='Этап ремонта'),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_or_plate',
            field=models.CharField(blank=True, max_length=64, verbose_name='VIN / госномер'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='BYN', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to='core.telegramuser', verbose_name='Изменил'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=64, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
