# Generated by Django 5.2.1 on 2026-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_car_status_554294_idx_core_car_status_f133b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id фото авто'),
        ),
    ]
