# Generated by Django 5.2.1 on 2026-06-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_car_photo_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_id', models.CharField(max_length=255, verbose_name='Telegram file_id фото дефектовки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_photos', to='core.car', verbose_name='Автомобиль')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_photos', to='core.telegramuser', verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Фото дефектовки',
                'verbose_name_plural': 'Фото дефектовки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', '-created_at'], name='core_defect_car_id_949794_idx')],
            },
        ),
    ]
