# Generated by Django 5.2.1 on 2026-06-12 07:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_defectphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь админки',
                'verbose_name_plural': 'Пользователи админки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото авто'),
        ),
        migrations.AddField(
            model_name='defectphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='defect_photos/', verbose_name='Фото дефектовки'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, upload_to='expense_receipts/', verbose_name='Фото расхода / чека'),
        ),
        migrations.AlterField(
            model_name='car',
            name='repair_stage',
            field=models.CharField(choices=[('accepted', 'Принят в работу'), ('defect', 'Дефектовка с фото'), ('waiting_parts', 'Ожидание деталей'), ('body_work', 'Кузовные работы'), ('paint_assembly', 'Подготовка/покраска/сборка'), ('ready', 'Готов к выдаче'), ('done', 'Завершен')], default='accepted', max_length=32, verbose_name='Этап ремонта'),
        ),
        migrations.AlterField(
            model_name='defectphoto',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id фото дефектовки'),
        ),
    ]
