# Generated by Django 5.2.1 on 2026-06-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminuserproxy_car_car_photo_defectphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo_file_id',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото авто'),
        ),
        migrations.AlterField(
            model_name='defectphoto',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото дефектовки'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo_file_id',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото чека'),
        ),
    ]
