# Generated by Django 5.2.1 on 2026-06-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_car_car_photo_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_id', models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото авто')),
                ('image', models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото авто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.car', verbose_name='Автомобиль')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_photos', to='core.telegramuser', verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобилей',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['car', 'created_at'], name='core_carpho_car_id_4428f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_id', models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото расхода')),
                ('image', models.ImageField(blank=True, upload_to='expense_receipts/', verbose_name='Фото расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.expense', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Фото расхода',
                'verbose_name_plural': 'Фото расходов',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['expense', 'created_at'], name='core_expens_expense_83949d_idx')],
            },
        ),
    ]
