# Generated by Django 5.2.1 on 2026-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carphoto_expensephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_photo',
            field=models.ImageField(blank=True, upload_to='vin_photos/', verbose_name='Фото VIN'),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_photo_file_id',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telegram file_id фото VIN'),
        ),
    ]
